version: '3.8'

services:
  supermarket_web:
    container_name: ${WEB_DOCKER_CONTAINER_NAME}
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./.env
    depends_on:
      - supermarket_db

  supermarket_db:
    container_name: ${DB_DOCKER_CONTAINER_NAME}
    build:
      context: ./Dockerfiles/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
